// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CloudSyncPacket.proto

package uk.co.bbc.rd.cloudsync;

public final class CloudSyncPacket {
  private CloudSyncPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code CloudSyncMessages.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JOIN_REQ = 0;</code>
     */
    JOIN_REQ(0),
    /**
     * <code>JOIN_RESP = 1;</code>
     */
    JOIN_RESP(1),
    /**
     * <code>DEVICE_REQ = 2;</code>
     */
    DEVICE_REQ(2),
    /**
     * <code>DEVICE_RESP = 3;</code>
     */
    DEVICE_RESP(3),
    /**
     * <code>LEAVE_REQ = 4;</code>
     */
    LEAVE_REQ(4),
    /**
     * <code>LEAVE_RESP = 5;</code>
     */
    LEAVE_RESP(5),
    /**
     * <code>TIMELINE_REG_REQ = 6;</code>
     */
    TIMELINE_REG_REQ(6),
    /**
     * <code>TIMELINE_REG_RESP = 7;</code>
     */
    TIMELINE_REG_RESP(7),
    /**
     * <code>TIMELINE_DEREG_REQ = 8;</code>
     */
    TIMELINE_DEREG_REQ(8),
    /**
     * <code>TIMELINE_DEREG_RESP = 9;</code>
     */
    TIMELINE_DEREG_RESP(9),
    /**
     * <code>TIMELINE_REQ = 10;</code>
     */
    TIMELINE_REQ(10),
    /**
     * <code>TIMELINE_QUERY = 11;</code>
     */
    TIMELINE_QUERY(11),
    /**
     * <code>TIMELINE_RESP = 12;</code>
     */
    TIMELINE_RESP(12),
    /**
     * <code>TIMELINE_SUB_REQ = 13;</code>
     */
    TIMELINE_SUB_REQ(13),
    /**
     * <code>TIMELINE_SUB_RESP = 14;</code>
     */
    TIMELINE_SUB_RESP(14),
    /**
     * <code>TIMELINE_UPDATE_REQ = 15;</code>
     */
    TIMELINE_UPDATE_REQ(15),
    /**
     * <code>TIMELINE_UPDATE_RESP = 16;</code>
     */
    TIMELINE_UPDATE_RESP(16),
    /**
     * <code>STOP_TIMELINE_UPDATE_REQ = 17;</code>
     */
    STOP_TIMELINE_UPDATE_REQ(17),
    /**
     * <code>TIMELINE_UPDATE = 18;</code>
     */
    TIMELINE_UPDATE(18),
    /**
     * <code>CONTENT_ID_CHANGE = 19;</code>
     */
    CONTENT_ID_CHANGE(19),
    /**
     * <code>DEVICE_STATUS = 20;</code>
     */
    DEVICE_STATUS(20),
    /**
     * <code>UNEXPECTED_DEVICE_EXIT = 21;</code>
     */
    UNEXPECTED_DEVICE_EXIT(21),
    /**
     * <code>SYNC_TIMELINES_AVAIL = 22;</code>
     */
    SYNC_TIMELINES_AVAIL(22),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>JOIN_REQ = 0;</code>
     */
    public static final int JOIN_REQ_VALUE = 0;
    /**
     * <code>JOIN_RESP = 1;</code>
     */
    public static final int JOIN_RESP_VALUE = 1;
    /**
     * <code>DEVICE_REQ = 2;</code>
     */
    public static final int DEVICE_REQ_VALUE = 2;
    /**
     * <code>DEVICE_RESP = 3;</code>
     */
    public static final int DEVICE_RESP_VALUE = 3;
    /**
     * <code>LEAVE_REQ = 4;</code>
     */
    public static final int LEAVE_REQ_VALUE = 4;
    /**
     * <code>LEAVE_RESP = 5;</code>
     */
    public static final int LEAVE_RESP_VALUE = 5;
    /**
     * <code>TIMELINE_REG_REQ = 6;</code>
     */
    public static final int TIMELINE_REG_REQ_VALUE = 6;
    /**
     * <code>TIMELINE_REG_RESP = 7;</code>
     */
    public static final int TIMELINE_REG_RESP_VALUE = 7;
    /**
     * <code>TIMELINE_DEREG_REQ = 8;</code>
     */
    public static final int TIMELINE_DEREG_REQ_VALUE = 8;
    /**
     * <code>TIMELINE_DEREG_RESP = 9;</code>
     */
    public static final int TIMELINE_DEREG_RESP_VALUE = 9;
    /**
     * <code>TIMELINE_REQ = 10;</code>
     */
    public static final int TIMELINE_REQ_VALUE = 10;
    /**
     * <code>TIMELINE_QUERY = 11;</code>
     */
    public static final int TIMELINE_QUERY_VALUE = 11;
    /**
     * <code>TIMELINE_RESP = 12;</code>
     */
    public static final int TIMELINE_RESP_VALUE = 12;
    /**
     * <code>TIMELINE_SUB_REQ = 13;</code>
     */
    public static final int TIMELINE_SUB_REQ_VALUE = 13;
    /**
     * <code>TIMELINE_SUB_RESP = 14;</code>
     */
    public static final int TIMELINE_SUB_RESP_VALUE = 14;
    /**
     * <code>TIMELINE_UPDATE_REQ = 15;</code>
     */
    public static final int TIMELINE_UPDATE_REQ_VALUE = 15;
    /**
     * <code>TIMELINE_UPDATE_RESP = 16;</code>
     */
    public static final int TIMELINE_UPDATE_RESP_VALUE = 16;
    /**
     * <code>STOP_TIMELINE_UPDATE_REQ = 17;</code>
     */
    public static final int STOP_TIMELINE_UPDATE_REQ_VALUE = 17;
    /**
     * <code>TIMELINE_UPDATE = 18;</code>
     */
    public static final int TIMELINE_UPDATE_VALUE = 18;
    /**
     * <code>CONTENT_ID_CHANGE = 19;</code>
     */
    public static final int CONTENT_ID_CHANGE_VALUE = 19;
    /**
     * <code>DEVICE_STATUS = 20;</code>
     */
    public static final int DEVICE_STATUS_VALUE = 20;
    /**
     * <code>UNEXPECTED_DEVICE_EXIT = 21;</code>
     */
    public static final int UNEXPECTED_DEVICE_EXIT_VALUE = 21;
    /**
     * <code>SYNC_TIMELINES_AVAIL = 22;</code>
     */
    public static final int SYNC_TIMELINES_AVAIL_VALUE = 22;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return JOIN_REQ;
        case 1: return JOIN_RESP;
        case 2: return DEVICE_REQ;
        case 3: return DEVICE_RESP;
        case 4: return LEAVE_REQ;
        case 5: return LEAVE_RESP;
        case 6: return TIMELINE_REG_REQ;
        case 7: return TIMELINE_REG_RESP;
        case 8: return TIMELINE_DEREG_REQ;
        case 9: return TIMELINE_DEREG_RESP;
        case 10: return TIMELINE_REQ;
        case 11: return TIMELINE_QUERY;
        case 12: return TIMELINE_RESP;
        case 13: return TIMELINE_SUB_REQ;
        case 14: return TIMELINE_SUB_RESP;
        case 15: return TIMELINE_UPDATE_REQ;
        case 16: return TIMELINE_UPDATE_RESP;
        case 17: return STOP_TIMELINE_UPDATE_REQ;
        case 18: return TIMELINE_UPDATE;
        case 19: return CONTENT_ID_CHANGE;
        case 20: return DEVICE_STATUS;
        case 21: return UNEXPECTED_DEVICE_EXIT;
        case 22: return SYNC_TIMELINES_AVAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return uk.co.bbc.rd.cloudsync.CloudSyncPacket.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CloudSyncMessages.MessageType)
  }

  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CloudSyncMessages.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CloudSyncMessages.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.CloudSyncMessages.Header header = 1;</code>
     * @return The header.
     */
    uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header getHeader();
    /**
     * <code>.CloudSyncMessages.Header header = 1;</code>
     */
    uk.co.bbc.rd.cloudsync.CloudSyncPacket.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code CloudSyncMessages.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CloudSyncMessages.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet.class, uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header header_;
    /**
     * <code>.CloudSyncMessages.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.CloudSyncMessages.Header header = 1;</code>
     * @return The header.
     */
    public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header getHeader() {
      return header_ == null ? uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.CloudSyncMessages.Header header = 1;</code>
     */
    public uk.co.bbc.rd.cloudsync.CloudSyncPacket.HeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet)) {
        return super.equals(obj);
      }
      uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet other = (uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CloudSyncMessages.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CloudSyncMessages.Packet)
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet.class, uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet.Builder.class);
      }

      // Construct using uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Packet_descriptor;
      }

      @java.lang.Override
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet getDefaultInstanceForType() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet build() {
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet buildPartial() {
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet result = new uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet) {
          return mergeFrom((uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet other) {
        if (other == uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header, uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder, uk.co.bbc.rd.cloudsync.CloudSyncPacket.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       * @return The header.
       */
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       */
      public Builder setHeader(uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       */
      public Builder setHeader(
          uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       */
      public Builder mergeHeader(uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       */
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       */
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.CloudSyncMessages.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header, uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder, uk.co.bbc.rd.cloudsync.CloudSyncPacket.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header, uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder, uk.co.bbc.rd.cloudsync.CloudSyncPacket.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       * @return The payload.
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CloudSyncMessages.Packet)
    }

    // @@protoc_insertion_point(class_scope:CloudSyncMessages.Packet)
    private static final uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet();
    }

    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CloudSyncMessages.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
     * @return The enum value for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
     * @return The msgType.
     */
    uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType getMsgType();

    /**
     * <code>string sessionID = 2;</code>
     * @return The sessionID.
     */
    java.lang.String getSessionID();
    /**
     * <code>string sessionID = 2;</code>
     * @return The bytes for sessionID.
     */
    com.google.protobuf.ByteString
        getSessionIDBytes();

    /**
     * <code>string messageID = 3;</code>
     * @return The messageID.
     */
    java.lang.String getMessageID();
    /**
     * <code>string messageID = 3;</code>
     * @return The bytes for messageID.
     */
    com.google.protobuf.ByteString
        getMessageIDBytes();

    /**
     * <code>string version = 4;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 4;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string senderID = 5;</code>
     * @return The senderID.
     */
    java.lang.String getSenderID();
    /**
     * <code>string senderID = 5;</code>
     * @return The bytes for senderID.
     */
    com.google.protobuf.ByteString
        getSenderIDBytes();

    /**
     * <code>string responseChannel = 6;</code>
     * @return The responseChannel.
     */
    java.lang.String getResponseChannel();
    /**
     * <code>string responseChannel = 6;</code>
     * @return The bytes for responseChannel.
     */
    com.google.protobuf.ByteString
        getResponseChannelBytes();

    /**
     * <code>int32 responseCode = 7;</code>
     * @return The responseCode.
     */
    int getResponseCode();
  }
  /**
   * Protobuf type {@code CloudSyncMessages.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CloudSyncMessages.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      msgType_ = 0;
      sessionID_ = "";
      messageID_ = "";
      version_ = "";
      senderID_ = "";
      responseChannel_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionID_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              messageID_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              senderID_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              responseChannel_ = s;
              break;
            }
            case 56: {

              responseCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.class, uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder.class);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
     * @return The enum value for msgType.
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
     * @return The msgType.
     */
    public uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType getMsgType() {
      @SuppressWarnings("deprecation")
      uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType result = uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType.valueOf(msgType_);
      return result == null ? uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType.UNRECOGNIZED : result;
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sessionID_;
    /**
     * <code>string sessionID = 2;</code>
     * @return The sessionID.
     */
    public java.lang.String getSessionID() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionID_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionID = 2;</code>
     * @return The bytes for sessionID.
     */
    public com.google.protobuf.ByteString
        getSessionIDBytes() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object messageID_;
    /**
     * <code>string messageID = 3;</code>
     * @return The messageID.
     */
    public java.lang.String getMessageID() {
      java.lang.Object ref = messageID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageID_ = s;
        return s;
      }
    }
    /**
     * <code>string messageID = 3;</code>
     * @return The bytes for messageID.
     */
    public com.google.protobuf.ByteString
        getMessageIDBytes() {
      java.lang.Object ref = messageID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 4;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 4;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERID_FIELD_NUMBER = 5;
    private volatile java.lang.Object senderID_;
    /**
     * <code>string senderID = 5;</code>
     * @return The senderID.
     */
    public java.lang.String getSenderID() {
      java.lang.Object ref = senderID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderID_ = s;
        return s;
      }
    }
    /**
     * <code>string senderID = 5;</code>
     * @return The bytes for senderID.
     */
    public com.google.protobuf.ByteString
        getSenderIDBytes() {
      java.lang.Object ref = senderID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECHANNEL_FIELD_NUMBER = 6;
    private volatile java.lang.Object responseChannel_;
    /**
     * <code>string responseChannel = 6;</code>
     * @return The responseChannel.
     */
    public java.lang.String getResponseChannel() {
      java.lang.Object ref = responseChannel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseChannel_ = s;
        return s;
      }
    }
    /**
     * <code>string responseChannel = 6;</code>
     * @return The bytes for responseChannel.
     */
    public com.google.protobuf.ByteString
        getResponseChannelBytes() {
      java.lang.Object ref = responseChannel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseChannel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 7;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 7;</code>
     * @return The responseCode.
     */
    public int getResponseCode() {
      return responseCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType.JOIN_REQ.getNumber()) {
        output.writeEnum(1, msgType_);
      }
      if (!getSessionIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionID_);
      }
      if (!getMessageIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageID_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
      }
      if (!getSenderIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, senderID_);
      }
      if (!getResponseChannelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, responseChannel_);
      }
      if (responseCode_ != 0) {
        output.writeInt32(7, responseCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType.JOIN_REQ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_);
      }
      if (!getSessionIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionID_);
      }
      if (!getMessageIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageID_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
      }
      if (!getSenderIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, senderID_);
      }
      if (!getResponseChannelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, responseChannel_);
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, responseCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header)) {
        return super.equals(obj);
      }
      uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header other = (uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header) obj;

      if (msgType_ != other.msgType_) return false;
      if (!getSessionID()
          .equals(other.getSessionID())) return false;
      if (!getMessageID()
          .equals(other.getMessageID())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getSenderID()
          .equals(other.getSenderID())) return false;
      if (!getResponseChannel()
          .equals(other.getResponseChannel())) return false;
      if (getResponseCode()
          != other.getResponseCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionID().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageID().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderID().hashCode();
      hash = (37 * hash) + RESPONSECHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getResponseChannel().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CloudSyncMessages.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CloudSyncMessages.Header)
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.class, uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.Builder.class);
      }

      // Construct using uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        sessionID_ = "";

        messageID_ = "";

        version_ = "";

        senderID_ = "";

        responseChannel_ = "";

        responseCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.internal_static_CloudSyncMessages_Header_descriptor;
      }

      @java.lang.Override
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header getDefaultInstanceForType() {
        return uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.getDefaultInstance();
      }

      @java.lang.Override
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header build() {
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header buildPartial() {
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header result = new uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header(this);
        result.msgType_ = msgType_;
        result.sessionID_ = sessionID_;
        result.messageID_ = messageID_;
        result.version_ = version_;
        result.senderID_ = senderID_;
        result.responseChannel_ = responseChannel_;
        result.responseCode_ = responseCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header) {
          return mergeFrom((uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header other) {
        if (other == uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header.getDefaultInstance()) return this;
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (!other.getSessionID().isEmpty()) {
          sessionID_ = other.sessionID_;
          onChanged();
        }
        if (!other.getMessageID().isEmpty()) {
          messageID_ = other.messageID_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getSenderID().isEmpty()) {
          senderID_ = other.senderID_;
          onChanged();
        }
        if (!other.getResponseChannel().isEmpty()) {
          responseChannel_ = other.responseChannel_;
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
       * @return The enum value for msgType.
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
       * @param value The enum value for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
       * @return The msgType.
       */
      public uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType getMsgType() {
        @SuppressWarnings("deprecation")
        uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType result = uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType.valueOf(msgType_);
        return result == null ? uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(uk.co.bbc.rd.cloudsync.CloudSyncPacket.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CloudSyncMessages.MessageType msgType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sessionID_ = "";
      /**
       * <code>string sessionID = 2;</code>
       * @return The sessionID.
       */
      public java.lang.String getSessionID() {
        java.lang.Object ref = sessionID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sessionID = 2;</code>
       * @return The bytes for sessionID.
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        java.lang.Object ref = sessionID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionID = 2;</code>
       * @param value The sessionID to set.
       * @return This builder for chaining.
       */
      public Builder setSessionID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionID() {
        
        sessionID_ = getDefaultInstance().getSessionID();
        onChanged();
        return this;
      }
      /**
       * <code>string sessionID = 2;</code>
       * @param value The bytes for sessionID to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageID_ = "";
      /**
       * <code>string messageID = 3;</code>
       * @return The messageID.
       */
      public java.lang.String getMessageID() {
        java.lang.Object ref = messageID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageID = 3;</code>
       * @return The bytes for messageID.
       */
      public com.google.protobuf.ByteString
          getMessageIDBytes() {
        java.lang.Object ref = messageID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageID = 3;</code>
       * @param value The messageID to set.
       * @return This builder for chaining.
       */
      public Builder setMessageID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageID = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageID() {
        
        messageID_ = getDefaultInstance().getMessageID();
        onChanged();
        return this;
      }
      /**
       * <code>string messageID = 3;</code>
       * @param value The bytes for messageID to set.
       * @return This builder for chaining.
       */
      public Builder setMessageIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 4;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 4;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 4;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 4;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderID_ = "";
      /**
       * <code>string senderID = 5;</code>
       * @return The senderID.
       */
      public java.lang.String getSenderID() {
        java.lang.Object ref = senderID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderID = 5;</code>
       * @return The bytes for senderID.
       */
      public com.google.protobuf.ByteString
          getSenderIDBytes() {
        java.lang.Object ref = senderID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderID = 5;</code>
       * @param value The senderID to set.
       * @return This builder for chaining.
       */
      public Builder setSenderID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderID = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderID() {
        
        senderID_ = getDefaultInstance().getSenderID();
        onChanged();
        return this;
      }
      /**
       * <code>string senderID = 5;</code>
       * @param value The bytes for senderID to set.
       * @return This builder for chaining.
       */
      public Builder setSenderIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object responseChannel_ = "";
      /**
       * <code>string responseChannel = 6;</code>
       * @return The responseChannel.
       */
      public java.lang.String getResponseChannel() {
        java.lang.Object ref = responseChannel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseChannel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseChannel = 6;</code>
       * @return The bytes for responseChannel.
       */
      public com.google.protobuf.ByteString
          getResponseChannelBytes() {
        java.lang.Object ref = responseChannel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseChannel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseChannel = 6;</code>
       * @param value The responseChannel to set.
       * @return This builder for chaining.
       */
      public Builder setResponseChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseChannel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseChannel = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseChannel() {
        
        responseChannel_ = getDefaultInstance().getResponseChannel();
        onChanged();
        return this;
      }
      /**
       * <code>string responseChannel = 6;</code>
       * @param value The bytes for responseChannel to set.
       * @return This builder for chaining.
       */
      public Builder setResponseChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseChannel_ = value;
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 7;</code>
       * @return The responseCode.
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 7;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CloudSyncMessages.Header)
    }

    // @@protoc_insertion_point(class_scope:CloudSyncMessages.Header)
    private static final uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header();
    }

    public static uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public uk.co.bbc.rd.cloudsync.CloudSyncPacket.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CloudSyncMessages_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CloudSyncMessages_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CloudSyncMessages_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CloudSyncMessages_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CloudSyncPacket.proto\022\021CloudSyncMessag" +
      "es\"D\n\006Packet\022)\n\006header\030\001 \001(\0132\031.CloudSync" +
      "Messages.Header\022\017\n\007payload\030\002 \001(\014\"\261\001\n\006Hea" +
      "der\022/\n\007msgType\030\001 \001(\0162\036.CloudSyncMessages" +
      ".MessageType\022\021\n\tsessionID\030\002 \001(\t\022\021\n\tmessa" +
      "geID\030\003 \001(\t\022\017\n\007version\030\004 \001(\t\022\020\n\010senderID\030" +
      "\005 \001(\t\022\027\n\017responseChannel\030\006 \001(\t\022\024\n\014respon" +
      "seCode\030\007 \001(\005*\364\003\n\013MessageType\022\014\n\010JOIN_REQ" +
      "\020\000\022\r\n\tJOIN_RESP\020\001\022\016\n\nDEVICE_REQ\020\002\022\017\n\013DEV" +
      "ICE_RESP\020\003\022\r\n\tLEAVE_REQ\020\004\022\016\n\nLEAVE_RESP\020" +
      "\005\022\024\n\020TIMELINE_REG_REQ\020\006\022\025\n\021TIMELINE_REG_" +
      "RESP\020\007\022\026\n\022TIMELINE_DEREG_REQ\020\010\022\027\n\023TIMELI" +
      "NE_DEREG_RESP\020\t\022\020\n\014TIMELINE_REQ\020\n\022\022\n\016TIM" +
      "ELINE_QUERY\020\013\022\021\n\rTIMELINE_RESP\020\014\022\024\n\020TIME" +
      "LINE_SUB_REQ\020\r\022\025\n\021TIMELINE_SUB_RESP\020\016\022\027\n" +
      "\023TIMELINE_UPDATE_REQ\020\017\022\030\n\024TIMELINE_UPDAT" +
      "E_RESP\020\020\022\034\n\030STOP_TIMELINE_UPDATE_REQ\020\021\022\023" +
      "\n\017TIMELINE_UPDATE\020\022\022\025\n\021CONTENT_ID_CHANGE" +
      "\020\023\022\021\n\rDEVICE_STATUS\020\024\022\032\n\026UNEXPECTED_DEVI" +
      "CE_EXIT\020\025\022\030\n\024SYNC_TIMELINES_AVAIL\020\026B)\n\026u" +
      "k.co.bbc.rd.cloudsyncB\017CloudSyncPacketb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CloudSyncMessages_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CloudSyncMessages_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CloudSyncMessages_Packet_descriptor,
        new java.lang.String[] { "Header", "Payload", });
    internal_static_CloudSyncMessages_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CloudSyncMessages_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CloudSyncMessages_Header_descriptor,
        new java.lang.String[] { "MsgType", "SessionID", "MessageID", "Version", "SenderID", "ResponseChannel", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
